// 枚举文件，该项目中用到的枚举值都可在此找到
//公式文本类型，一种是MathML，一种是Latex
//具体的差异和文本格式可以在网上查找相关资料，是规范化的文本格式
var EDTextType;
(function (EDTextType) {
    EDTextType[EDTextType["MathML"] = 0] = "MathML";
    EDTextType[EDTextType["Latex"] = 1] = "Latex";
})(EDTextType || (EDTextType = {}));
;
//mathml节点类型，
//这是规范化的节点命名，具体可以在https://developer.mozilla.org/en-US/docs/Web/MathML/Element 等资料网页查阅
var EDMathMlNodeType;
(function (EDMathMlNodeType) {
    EDMathMlNodeType[EDMathMlNodeType["NoNode"] = 0] = "NoNode";
    EDMathMlNodeType[EDMathMlNodeType["MiNode"] = 1] = "MiNode";
    EDMathMlNodeType[EDMathMlNodeType["MnNode"] = 2] = "MnNode";
    EDMathMlNodeType[EDMathMlNodeType["MfracNode"] = 3] = "MfracNode";
    EDMathMlNodeType[EDMathMlNodeType["MrowNode"] = 4] = "MrowNode";
    EDMathMlNodeType[EDMathMlNodeType["MsqrtNode"] = 5] = "MsqrtNode";
    EDMathMlNodeType[EDMathMlNodeType["MrootNode"] = 6] = "MrootNode";
    EDMathMlNodeType[EDMathMlNodeType["MsupNode"] = 7] = "MsupNode";
    EDMathMlNodeType[EDMathMlNodeType["MsubNode"] = 8] = "MsubNode";
    EDMathMlNodeType[EDMathMlNodeType["MsubsupNode"] = 9] = "MsubsupNode";
    EDMathMlNodeType[EDMathMlNodeType["MoNode"] = 10] = "MoNode";
    EDMathMlNodeType[EDMathMlNodeType["MstyleNode"] = 11] = "MstyleNode";
    EDMathMlNodeType[EDMathMlNodeType["MencloseNode"] = 12] = "MencloseNode";
    EDMathMlNodeType[EDMathMlNodeType["TextNode"] = 13] = "TextNode";
    EDMathMlNodeType[EDMathMlNodeType["MphantomNode"] = 14] = "MphantomNode";
    EDMathMlNodeType[EDMathMlNodeType["MfencedNode"] = 15] = "MfencedNode";
    EDMathMlNodeType[EDMathMlNodeType["MtableNode"] = 16] = "MtableNode";
    EDMathMlNodeType[EDMathMlNodeType["MtrNode"] = 17] = "MtrNode";
    EDMathMlNodeType[EDMathMlNodeType["MtdNode"] = 18] = "MtdNode";
    EDMathMlNodeType[EDMathMlNodeType["MoverNode"] = 19] = "MoverNode";
    EDMathMlNodeType[EDMathMlNodeType["MunderNode"] = 20] = "MunderNode";
    EDMathMlNodeType[EDMathMlNodeType["MunderoverNode"] = 21] = "MunderoverNode";
    EDMathMlNodeType[EDMathMlNodeType["MprescriptsNode"] = 22] = "MprescriptsNode";
    EDMathMlNodeType[EDMathMlNodeType["NoneNode"] = 23] = "NoneNode";
    EDMathMlNodeType[EDMathMlNodeType["MmultiscriptsNode"] = 24] = "MmultiscriptsNode";
    EDMathMlNodeType[EDMathMlNodeType["MerrorNode"] = 25] = "MerrorNode";
    EDMathMlNodeType[EDMathMlNodeType["MtextNode"] = 26] = "MtextNode";
    EDMathMlNodeType[EDMathMlNodeType["MpaddedNode"] = 27] = "MpaddedNode";
    EDMathMlNodeType[EDMathMlNodeType["MspaceNode"] = 28] = "MspaceNode";
    EDMathMlNodeType[EDMathMlNodeType["MalignMarkNode"] = 29] = "MalignMarkNode";
    EDMathMlNodeType[EDMathMlNodeType["UnknownNode"] = 30] = "UnknownNode";
})(EDMathMlNodeType || (EDMathMlNodeType = {}));
;
//公式索引值
//一个公式索引值相当于一个命令码，使用insertFormula( index: EDMmlFormulaIndex)调用对应的公式操作
//索引值从100000起步，小于该数值的采取unicode码的转换，比如insertFormula(8736)是插入'∠'符号，
//'∠'的unicode码是&#8736;(十进制)或者&#x2220;(十六进制),代码中的unicode码统一使用十六进制处理
//其中symbol_length之前均为符号索引值(只插入一个特殊字符)
//symbol_length之后为公式节点结构的索引值(插入一系列的节点结构)
//一些命名缩写说明：_o = over; _u = under; _b = sub;  _p = sup;  _uo = underover; _bp = subsup
//                _i = index; _l = left; _r = right; _s = single
var EDMmlFormulaIndex;
(function (EDMmlFormulaIndex) {
    //按mathytype界面分类
    EDMmlFormulaIndex[EDMmlFormulaIndex["le"] = 100000] = "le";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ge"] = 100001] = "ge";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ll"] = 100002] = "ll";
    EDMmlFormulaIndex[EDMmlFormulaIndex["gg"] = 100003] = "gg";
    EDMmlFormulaIndex[EDMmlFormulaIndex["prec"] = 100004] = "prec";
    EDMmlFormulaIndex[EDMmlFormulaIndex["succ"] = 100005] = "succ";
    EDMmlFormulaIndex[EDMmlFormulaIndex["triangleleft"] = 100006] = "triangleleft";
    EDMmlFormulaIndex[EDMmlFormulaIndex["triangleright"] = 100007] = "triangleright";
    EDMmlFormulaIndex[EDMmlFormulaIndex["thicksim"] = 100008] = "thicksim";
    EDMmlFormulaIndex[EDMmlFormulaIndex["asymp"] = 100009] = "asymp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["simeq"] = 100010] = "simeq";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cong"] = 100011] = "cong";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ne"] = 100012] = "ne";
    EDMmlFormulaIndex[EDMmlFormulaIndex["equiv"] = 100013] = "equiv";
    EDMmlFormulaIndex[EDMmlFormulaIndex["triangleq"] = 100014] = "triangleq";
    EDMmlFormulaIndex[EDMmlFormulaIndex["hateq"] = 100015] = "hateq";
    EDMmlFormulaIndex[EDMmlFormulaIndex["doteq"] = 100016] = "doteq";
    EDMmlFormulaIndex[EDMmlFormulaIndex["prop"] = 100017] = "prop";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Indentation"] = 100018] = "Indentation";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Space_1"] = 100019] = "Space_1";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Space_2"] = 100020] = "Space_2";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Space_3"] = 100021] = "Space_3";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Space_4"] = 100022] = "Space_4";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Space_5"] = 100023] = "Space_5";
    EDMmlFormulaIndex[EDMmlFormulaIndex["hellip"] = 100024] = "hellip";
    EDMmlFormulaIndex[EDMmlFormulaIndex["mellip"] = 100025] = "mellip";
    EDMmlFormulaIndex[EDMmlFormulaIndex["vellip"] = 100026] = "vellip";
    EDMmlFormulaIndex[EDMmlFormulaIndex["urellip"] = 100027] = "urellip";
    EDMmlFormulaIndex[EDMmlFormulaIndex["rrellip"] = 100028] = "rrellip";
    EDMmlFormulaIndex[EDMmlFormulaIndex["plusmn"] = 100029] = "plusmn";
    EDMmlFormulaIndex[EDMmlFormulaIndex["minusPlus"] = 100030] = "minusPlus";
    EDMmlFormulaIndex[EDMmlFormulaIndex["times"] = 100031] = "times";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lowast"] = 100032] = "lowast";
    EDMmlFormulaIndex[EDMmlFormulaIndex["div"] = 100033] = "div";
    EDMmlFormulaIndex[EDMmlFormulaIndex["oplus"] = 100034] = "oplus";
    EDMmlFormulaIndex[EDMmlFormulaIndex["otimes"] = 100035] = "otimes";
    EDMmlFormulaIndex[EDMmlFormulaIndex["odot"] = 100036] = "odot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sdot"] = 100037] = "sdot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["centerdot"] = 100038] = "centerdot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["bullet"] = 100039] = "bullet";
    EDMmlFormulaIndex[EDMmlFormulaIndex["scirc"] = 100040] = "scirc";
    EDMmlFormulaIndex[EDMmlFormulaIndex["langle"] = 100041] = "langle";
    EDMmlFormulaIndex[EDMmlFormulaIndex["rangle"] = 100042] = "rangle";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lobrk"] = 100043] = "lobrk";
    EDMmlFormulaIndex[EDMmlFormulaIndex["robrk"] = 100044] = "robrk";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftRightArr"] = 100045] = "LeftRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightArr"] = 100046] = "RightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftArr"] = 100047] = "LeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UpDownArrow"] = 100048] = "UpDownArrow";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UpArrow"] = 100049] = "UpArrow";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DownArrow"] = 100050] = "DownArrow";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleLeftRightArr"] = 100051] = "DoubleLeftRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleRightArr"] = 100052] = "DoubleRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleLeftArr"] = 100053] = "DoubleLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleUpDownArr"] = 100054] = "DoubleUpDownArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleUpArr"] = 100055] = "DoubleUpArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleDownArr"] = 100056] = "DoubleDownArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LLeftURightArr"] = 100057] = "LLeftURightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UpperRightArr"] = 100058] = "UpperRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LowerLeftArr"] = 100059] = "LowerLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ULeftLRightArr"] = 100060] = "ULeftLRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LowerRightArr"] = 100061] = "LowerRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UpperLeftArr"] = 100062] = "UpperLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightArrLeftArr"] = 100063] = "RightArrLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Equilibrium"] = 100064] = "Equilibrium";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightTeeArr"] = 100065] = "RightTeeArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["enter"] = 100066] = "enter";
    EDMmlFormulaIndex[EDMmlFormulaIndex["there4"] = 100067] = "there4";
    EDMmlFormulaIndex[EDMmlFormulaIndex["becaus"] = 100068] = "becaus";
    EDMmlFormulaIndex[EDMmlFormulaIndex["backepsilon"] = 100069] = "backepsilon";
    EDMmlFormulaIndex[EDMmlFormulaIndex["exist"] = 100070] = "exist";
    EDMmlFormulaIndex[EDMmlFormulaIndex["forall"] = 100071] = "forall";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Not"] = 100072] = "Not";
    EDMmlFormulaIndex[EDMmlFormulaIndex["And"] = 100073] = "And";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Or"] = 100074] = "Or";
    EDMmlFormulaIndex[EDMmlFormulaIndex["isin"] = 100075] = "isin";
    EDMmlFormulaIndex[EDMmlFormulaIndex["notin"] = 100076] = "notin";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cup"] = 100077] = "cup";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cap"] = 100078] = "cap";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sub"] = 100079] = "sub";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sup"] = 100080] = "sup";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sube"] = 100081] = "sube";
    EDMmlFormulaIndex[EDMmlFormulaIndex["supe"] = 100082] = "supe";
    EDMmlFormulaIndex[EDMmlFormulaIndex["nsub"] = 100083] = "nsub";
    EDMmlFormulaIndex[EDMmlFormulaIndex["empty"] = 100084] = "empty";
    EDMmlFormulaIndex[EDMmlFormulaIndex["part"] = 100085] = "part";
    EDMmlFormulaIndex[EDMmlFormulaIndex["wp"] = 100086] = "wp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Im"] = 100087] = "Im";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Re"] = 100088] = "Re";
    EDMmlFormulaIndex[EDMmlFormulaIndex["aleph"] = 100089] = "aleph";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Ropf"] = 100090] = "Ropf";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Zopf"] = 100091] = "Zopf";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Copf"] = 100092] = "Copf";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Qopf"] = 100093] = "Qopf";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Nopf"] = 100094] = "Nopf";
    EDMmlFormulaIndex[EDMmlFormulaIndex["infin"] = 100095] = "infin";
    EDMmlFormulaIndex[EDMmlFormulaIndex["hbar"] = 100096] = "hbar";
    EDMmlFormulaIndex[EDMmlFormulaIndex["hlambda"] = 100097] = "hlambda";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ell"] = 100098] = "ell";
    EDMmlFormulaIndex[EDMmlFormulaIndex["dagger"] = 100099] = "dagger";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Delta"] = 100100] = "Delta";
    EDMmlFormulaIndex[EDMmlFormulaIndex["nabla"] = 100101] = "nabla";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Omega"] = 100102] = "Omega";
    EDMmlFormulaIndex[EDMmlFormulaIndex["mho"] = 100103] = "mho";
    EDMmlFormulaIndex[EDMmlFormulaIndex["diamond"] = 100104] = "diamond";
    EDMmlFormulaIndex[EDMmlFormulaIndex["prod"] = 100105] = "prod";
    EDMmlFormulaIndex[EDMmlFormulaIndex["coprod"] = 100106] = "coprod";
    EDMmlFormulaIndex[EDMmlFormulaIndex["circ"] = 100107] = "circ";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ang"] = 100108] = "ang";
    EDMmlFormulaIndex[EDMmlFormulaIndex["measuredangle"] = 100109] = "measuredangle";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sphericalangle"] = 100110] = "sphericalangle";
    EDMmlFormulaIndex[EDMmlFormulaIndex["perp"] = 100111] = "perp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["parallel"] = 100112] = "parallel";
    EDMmlFormulaIndex[EDMmlFormulaIndex["bigtriangleup"] = 100113] = "bigtriangleup";
    EDMmlFormulaIndex[EDMmlFormulaIndex["square"] = 100114] = "square";
    EDMmlFormulaIndex[EDMmlFormulaIndex["rect"] = 100115] = "rect";
    EDMmlFormulaIndex[EDMmlFormulaIndex["quad"] = 100116] = "quad";
    EDMmlFormulaIndex[EDMmlFormulaIndex["bigcirc"] = 100117] = "bigcirc";
    EDMmlFormulaIndex[EDMmlFormulaIndex["alpha"] = 100118] = "alpha";
    EDMmlFormulaIndex[EDMmlFormulaIndex["beta"] = 100119] = "beta";
    EDMmlFormulaIndex[EDMmlFormulaIndex["chi"] = 100120] = "chi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["delta"] = 100121] = "delta";
    EDMmlFormulaIndex[EDMmlFormulaIndex["epsilon"] = 100122] = "epsilon";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lphi"] = 100123] = "lphi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["phi"] = 100124] = "phi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["gamma"] = 100125] = "gamma";
    EDMmlFormulaIndex[EDMmlFormulaIndex["eta"] = 100126] = "eta";
    EDMmlFormulaIndex[EDMmlFormulaIndex["iota"] = 100127] = "iota";
    EDMmlFormulaIndex[EDMmlFormulaIndex["kappa"] = 100128] = "kappa";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lambda"] = 100129] = "lambda";
    EDMmlFormulaIndex[EDMmlFormulaIndex["mu"] = 100130] = "mu";
    EDMmlFormulaIndex[EDMmlFormulaIndex["nu"] = 100131] = "nu";
    EDMmlFormulaIndex[EDMmlFormulaIndex["omicron"] = 100132] = "omicron";
    EDMmlFormulaIndex[EDMmlFormulaIndex["pi"] = 100133] = "pi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["piv"] = 100134] = "piv";
    EDMmlFormulaIndex[EDMmlFormulaIndex["theta"] = 100135] = "theta";
    EDMmlFormulaIndex[EDMmlFormulaIndex["thetasym"] = 100136] = "thetasym";
    EDMmlFormulaIndex[EDMmlFormulaIndex["rho"] = 100137] = "rho";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sigma"] = 100138] = "sigma";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sigmaf"] = 100139] = "sigmaf";
    EDMmlFormulaIndex[EDMmlFormulaIndex["tau"] = 100140] = "tau";
    EDMmlFormulaIndex[EDMmlFormulaIndex["upsilon"] = 100141] = "upsilon";
    EDMmlFormulaIndex[EDMmlFormulaIndex["omega"] = 100142] = "omega";
    EDMmlFormulaIndex[EDMmlFormulaIndex["xi"] = 100143] = "xi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["psi"] = 100144] = "psi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["zeta"] = 100145] = "zeta";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Alpha"] = 100146] = "Alpha";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Beta"] = 100147] = "Beta";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Chi"] = 100148] = "Chi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Epsilon"] = 100149] = "Epsilon";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Phi"] = 100150] = "Phi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Gamma"] = 100151] = "Gamma";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Eta"] = 100152] = "Eta";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Iota"] = 100153] = "Iota";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Kappa"] = 100154] = "Kappa";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Lambda"] = 100155] = "Lambda";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Mu"] = 100156] = "Mu";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Nu"] = 100157] = "Nu";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Omicron"] = 100158] = "Omicron";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Pi"] = 100159] = "Pi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Theta"] = 100160] = "Theta";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Rho"] = 100161] = "Rho";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Sigma"] = 100162] = "Sigma";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Tau"] = 100163] = "Tau";
    EDMmlFormulaIndex[EDMmlFormulaIndex["upsih"] = 100164] = "upsih";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Xi"] = 100165] = "Xi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Psi"] = 100166] = "Psi";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Zeta"] = 100167] = "Zeta";
    // 符号类型
    EDMmlFormulaIndex[EDMmlFormulaIndex["Symbol_LRightArrSLeftArr"] = 100168] = "Symbol_LRightArrSLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Symbol_SRightArrLLeftArr"] = 100169] = "Symbol_SRightArrLLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Symbol_LRightVerSLeftVer"] = 100170] = "Symbol_LRightVerSLeftVer";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Symbol_SRightVerLLeftVer"] = 100171] = "Symbol_SRightVerLLeftVer";
    //待完善，当前公式编辑器的界面中未使用
    EDMmlFormulaIndex[EDMmlFormulaIndex["sin"] = 100172] = "sin";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cos"] = 100173] = "cos";
    EDMmlFormulaIndex[EDMmlFormulaIndex["tan"] = 100174] = "tan";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sec"] = 100175] = "sec";
    EDMmlFormulaIndex[EDMmlFormulaIndex["csc"] = 100176] = "csc";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cot"] = 100177] = "cot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["arcsin"] = 100178] = "arcsin";
    EDMmlFormulaIndex[EDMmlFormulaIndex["arccos"] = 100179] = "arccos";
    EDMmlFormulaIndex[EDMmlFormulaIndex["arctan"] = 100180] = "arctan";
    EDMmlFormulaIndex[EDMmlFormulaIndex["arccot"] = 100181] = "arccot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["d"] = 100182] = "d";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lim"] = 100183] = "lim";
    EDMmlFormulaIndex[EDMmlFormulaIndex["log"] = 100184] = "log";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lg"] = 100185] = "lg";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ln"] = 100186] = "ln";
    EDMmlFormulaIndex[EDMmlFormulaIndex["exp"] = 100187] = "exp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ch"] = 100188] = "ch";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sh"] = 100189] = "sh";
    EDMmlFormulaIndex[EDMmlFormulaIndex["max"] = 100190] = "max";
    EDMmlFormulaIndex[EDMmlFormulaIndex["min"] = 100191] = "min";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ni"] = 100192] = "ni";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sum"] = 100193] = "sum";
    EDMmlFormulaIndex[EDMmlFormulaIndex["minus"] = 100194] = "minus";
    EDMmlFormulaIndex[EDMmlFormulaIndex["radic"] = 100195] = "radic";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lceil"] = 100196] = "lceil";
    EDMmlFormulaIndex[EDMmlFormulaIndex["rceil"] = 100197] = "rceil";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lfloor"] = 100198] = "lfloor";
    EDMmlFormulaIndex[EDMmlFormulaIndex["rfloor"] = 100199] = "rfloor";
    //DoubleInt, TripleInt,ContourInt, SurfaceInt, VolumeInt, ClockwiseContInt, CtClockwiseContInt, 
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongLeftArr"] = 100200] = "LongLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftTeeArr"] = 100201] = "LeftTeeArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DbLongLeftArr"] = 100202] = "DbLongLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongRightArr"] = 100203] = "LongRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DbLongRightArr"] = 100204] = "DbLongRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongLeftRightArr"] = 100205] = "LongLeftRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftArrRightArr"] = 100206] = "LeftArrRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ReverseEquilibrium"] = 100207] = "ReverseEquilibrium";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongRArrShortLArr"] = 100208] = "LongRArrShortLArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ShortRArrLongLArr"] = 100209] = "ShortRArrLongLArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Upsilon"] = 100210] = "Upsilon";
    //教育板块
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_a"] = 100211] = "key_a";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_b"] = 100212] = "key_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_c"] = 100213] = "key_c";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_d"] = 100214] = "key_d";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_e"] = 100215] = "key_e";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_f"] = 100216] = "key_f";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_g"] = 100217] = "key_g";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_h"] = 100218] = "key_h";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_i"] = 100219] = "key_i";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_j"] = 100220] = "key_j";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_k"] = 100221] = "key_k";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_l"] = 100222] = "key_l";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_m"] = 100223] = "key_m";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_n"] = 100224] = "key_n";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_o"] = 100225] = "key_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_p"] = 100226] = "key_p";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_q"] = 100227] = "key_q";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_r"] = 100228] = "key_r";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_s"] = 100229] = "key_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_t"] = 100230] = "key_t";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_u"] = 100231] = "key_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_v"] = 100232] = "key_v";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_w"] = 100233] = "key_w";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x"] = 100234] = "key_x";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_y"] = 100235] = "key_y";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_z"] = 100236] = "key_z";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_A"] = 100237] = "key_A";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_B"] = 100238] = "key_B";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_C"] = 100239] = "key_C";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_D"] = 100240] = "key_D";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_E"] = 100241] = "key_E";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_F"] = 100242] = "key_F";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_G"] = 100243] = "key_G";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_H"] = 100244] = "key_H";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_I"] = 100245] = "key_I";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_J"] = 100246] = "key_J";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_K"] = 100247] = "key_K";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_L"] = 100248] = "key_L";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_M"] = 100249] = "key_M";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_N"] = 100250] = "key_N";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_O"] = 100251] = "key_O";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_P"] = 100252] = "key_P";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_Q"] = 100253] = "key_Q";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_R"] = 100254] = "key_R";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_S"] = 100255] = "key_S";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_T"] = 100256] = "key_T";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_U"] = 100257] = "key_U";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_V"] = 100258] = "key_V";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_W"] = 100259] = "key_W";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_X"] = 100260] = "key_X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_Y"] = 100261] = "key_Y";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_Z"] = 100262] = "key_Z";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_1"] = 100263] = "key_1";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_2"] = 100264] = "key_2";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_3"] = 100265] = "key_3";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_4"] = 100266] = "key_4";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_5"] = 100267] = "key_5";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_6"] = 100268] = "key_6";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_7"] = 100269] = "key_7";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_8"] = 100270] = "key_8";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_9"] = 100271] = "key_9";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_0"] = 100272] = "key_0";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x21"] = 100273] = "key_x21";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x22"] = 100274] = "key_x22";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x23"] = 100275] = "key_x23";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x24"] = 100276] = "key_x24";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x25"] = 100277] = "key_x25";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x26"] = 100278] = "key_x26";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x27"] = 100279] = "key_x27";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x28"] = 100280] = "key_x28";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x29"] = 100281] = "key_x29";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x2B"] = 100282] = "key_x2B";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x2C"] = 100283] = "key_x2C";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x2D"] = 100284] = "key_x2D";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x2E"] = 100285] = "key_x2E";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x3A"] = 100286] = "key_x3A";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x3B"] = 100287] = "key_x3B";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x3C"] = 100288] = "key_x3C";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x3D"] = 100289] = "key_x3D";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x3E"] = 100290] = "key_x3E";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x3F"] = 100291] = "key_x3F";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x40"] = 100292] = "key_x40";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x5B"] = 100293] = "key_x5B";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x5D"] = 100294] = "key_x5D";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x7B"] = 100295] = "key_x7B";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x7D"] = 100296] = "key_x7D";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_xB0"] = 100297] = "key_xB0";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x58x61"] = 100298] = "key_x58x61";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x2032"] = 100299] = "key_x2032";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x2033"] = 100300] = "key_x2033";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_x225f"] = 100301] = "key_x225f";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_backspace"] = 100302] = "key_backspace";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_left"] = 100303] = "key_left";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_right"] = 100304] = "key_right";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_enter"] = 100305] = "key_enter";
    EDMmlFormulaIndex[EDMmlFormulaIndex["key_selectedAll"] = 100306] = "key_selectedAll";
    EDMmlFormulaIndex[EDMmlFormulaIndex["edusymbol_length"] = 100307] = "edusymbol_length";
    //
    EDMmlFormulaIndex[EDMmlFormulaIndex["symbol_length"] = 100308] = "symbol_length";
    //公式
    EDMmlFormulaIndex[EDMmlFormulaIndex["insertMrow"] = 100309] = "insertMrow";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Frac"] = 100310] = "Frac";
    EDMmlFormulaIndex[EDMmlFormulaIndex["FracBevelled"] = 100311] = "FracBevelled";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Frac_old"] = 100312] = "Frac_old";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Frac_s"] = 100313] = "Frac_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["FracBevelled_s"] = 100314] = "FracBevelled_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Sqrt"] = 100315] = "Sqrt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Root"] = 100316] = "Root";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_div"] = 100317] = "Enclose_div";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SubSup"] = 100318] = "SubSup";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Sub"] = 100319] = "Sub";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Sup"] = 100320] = "Sup";
    EDMmlFormulaIndex[EDMmlFormulaIndex["PreSubSup"] = 100321] = "PreSubSup";
    EDMmlFormulaIndex[EDMmlFormulaIndex["PreSub"] = 100322] = "PreSub";
    EDMmlFormulaIndex[EDMmlFormulaIndex["PreSup"] = 100323] = "PreSup";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Empty_uo"] = 100324] = "Empty_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Empty_u"] = 100325] = "Empty_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Empty_o"] = 100326] = "Empty_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Empty_bp"] = 100327] = "Empty_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Empty_b"] = 100328] = "Empty_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Empty_p"] = 100329] = "Empty_p";
    EDMmlFormulaIndex[EDMmlFormulaIndex["PreEmpty_p"] = 100330] = "PreEmpty_p";
    EDMmlFormulaIndex[EDMmlFormulaIndex["PreEmpty_b"] = 100331] = "PreEmpty_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["PreEmpty_bp"] = 100332] = "PreEmpty_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LargeEmpty_uo"] = 100333] = "LargeEmpty_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LargeEmpty_u"] = 100334] = "LargeEmpty_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LargeEmpty_o"] = 100335] = "LargeEmpty_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LargeEmpty_bp"] = 100336] = "LargeEmpty_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LargeEmpty_b"] = 100337] = "LargeEmpty_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LargeEmpty_p"] = 100338] = "LargeEmpty_p";
    EDMmlFormulaIndex[EDMmlFormulaIndex["PreLargeEmpty_p"] = 100339] = "PreLargeEmpty_p";
    EDMmlFormulaIndex[EDMmlFormulaIndex["PreLargeEmpty_b"] = 100340] = "PreLargeEmpty_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["PreLargeEmpty_bp"] = 100341] = "PreLargeEmpty_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_tablediv"] = 100342] = "Enclose_tablediv";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_tablediv2"] = 100343] = "Enclose_tablediv2";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Npart"] = 100344] = "Npart";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Infin"] = 100345] = "Infin";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Sum_uo"] = 100346] = "Sum_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Sum"] = 100347] = "Sum";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Sum_u"] = 100348] = "Sum_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Sum_bp"] = 100349] = "Sum_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Sum_b"] = 100350] = "Sum_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Product_uo"] = 100351] = "Product_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Product"] = 100352] = "Product";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Product_u"] = 100353] = "Product_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Product_bp"] = 100354] = "Product_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Product_b"] = 100355] = "Product_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CoProduct_uo"] = 100356] = "CoProduct_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CoProduct"] = 100357] = "CoProduct";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CoProduct_u"] = 100358] = "CoProduct_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CoProduct_bp"] = 100359] = "CoProduct_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CoProduct_b"] = 100360] = "CoProduct_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Intersection_uo"] = 100361] = "Intersection_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Intersection"] = 100362] = "Intersection";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Intersection_u"] = 100363] = "Intersection_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Intersection_bp"] = 100364] = "Intersection_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Intersection_b"] = 100365] = "Intersection_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Union_uo"] = 100366] = "Union_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Union"] = 100367] = "Union";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Union_u"] = 100368] = "Union_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Union_bp"] = 100369] = "Union_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Union_b"] = 100370] = "Union_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Lor_uo"] = 100371] = "Lor_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Lor"] = 100372] = "Lor";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Lor_u"] = 100373] = "Lor_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Lor_bp"] = 100374] = "Lor_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Lor_b"] = 100375] = "Lor_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Land_uo"] = 100376] = "Land_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Land"] = 100377] = "Land";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Land_u"] = 100378] = "Land_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Land_bp"] = 100379] = "Land_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Land_b"] = 100380] = "Land_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Int_u"] = 100381] = "Int_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Int_uo"] = 100382] = "Int_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Int"] = 100383] = "Int";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Int_bp"] = 100384] = "Int_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Int_b"] = 100385] = "Int_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleInt_u"] = 100386] = "DoubleInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleInt_uo"] = 100387] = "DoubleInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleInt"] = 100388] = "DoubleInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleInt_bp"] = 100389] = "DoubleInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleInt_b"] = 100390] = "DoubleInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["TripleInt_u"] = 100391] = "TripleInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["TripleInt_uo"] = 100392] = "TripleInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["TripleInt"] = 100393] = "TripleInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["TripleInt_bp"] = 100394] = "TripleInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["TripleInt_b"] = 100395] = "TripleInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["QuadrupleInt_u"] = 100396] = "QuadrupleInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["QuadrupleInt_uo"] = 100397] = "QuadrupleInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["QuadrupleInt"] = 100398] = "QuadrupleInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["QuadrupleInt_bp"] = 100399] = "QuadrupleInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["QuadrupleInt_b"] = 100400] = "QuadrupleInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ContourInt_u"] = 100401] = "ContourInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ContourInt_uo"] = 100402] = "ContourInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ContourInt"] = 100403] = "ContourInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ContourInt_bp"] = 100404] = "ContourInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ContourInt_b"] = 100405] = "ContourInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SurfaceInt_u"] = 100406] = "SurfaceInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SurfaceInt_uo"] = 100407] = "SurfaceInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SurfaceInt"] = 100408] = "SurfaceInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SurfaceInt_bp"] = 100409] = "SurfaceInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SurfaceInt_b"] = 100410] = "SurfaceInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["VolumeInt_u"] = 100411] = "VolumeInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["VolumeInt_uo"] = 100412] = "VolumeInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["VolumeInt"] = 100413] = "VolumeInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["VolumeInt_bp"] = 100414] = "VolumeInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["VolumeInt_b"] = 100415] = "VolumeInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseInt_u"] = 100416] = "ClockwiseInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseInt_uo"] = 100417] = "ClockwiseInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseInt"] = 100418] = "ClockwiseInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseInt_bp"] = 100419] = "ClockwiseInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseInt_b"] = 100420] = "ClockwiseInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseInt_u"] = 100421] = "CtClockwiseInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseInt_uo"] = 100422] = "CtClockwiseInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseInt"] = 100423] = "CtClockwiseInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseInt_bp"] = 100424] = "CtClockwiseInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseInt_b"] = 100425] = "CtClockwiseInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseContInt_u"] = 100426] = "ClockwiseContInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseContInt_uo"] = 100427] = "ClockwiseContInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseContInt"] = 100428] = "ClockwiseContInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseContInt_bp"] = 100429] = "ClockwiseContInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ClockwiseContInt_b"] = 100430] = "ClockwiseContInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseContInt_u"] = 100431] = "CtClockwiseContInt_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseContInt_uo"] = 100432] = "CtClockwiseContInt_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseContInt"] = 100433] = "CtClockwiseContInt";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseContInt_bp"] = 100434] = "CtClockwiseContInt_bp";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CtClockwiseContInt_b"] = 100435] = "CtClockwiseContInt_b";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_tl"] = 100436] = "Enclose_tl";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_tr"] = 100437] = "Enclose_tr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_bl"] = 100438] = "Enclose_bl";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_br"] = 100439] = "Enclose_br";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_box"] = 100440] = "Enclose_box";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_up"] = 100441] = "Enclose_up";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_down"] = 100442] = "Enclose_down";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_updown"] = 100443] = "Enclose_updown";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_ver"] = 100444] = "Enclose_ver";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclose_hor"] = 100445] = "Enclose_hor";
    //括号
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_lr"] = 100446] = "Parentheses_lr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_l"] = 100447] = "Parentheses_l";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_r"] = 100448] = "Parentheses_r";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_uo"] = 100449] = "Parentheses_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_u"] = 100450] = "Parentheses_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_o"] = 100451] = "Parentheses_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_iuo"] = 100452] = "Parentheses_iuo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_iu"] = 100453] = "Parentheses_iu";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_io"] = 100454] = "Parentheses_io";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_lr"] = 100455] = "SquareBracket_lr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_l"] = 100456] = "SquareBracket_l";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_r"] = 100457] = "SquareBracket_r";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_uo"] = 100458] = "SquareBracket_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_u"] = 100459] = "SquareBracket_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_o"] = 100460] = "SquareBracket_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_iuo"] = 100461] = "SquareBracket_iuo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_iu"] = 100462] = "SquareBracket_iu";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_io"] = 100463] = "SquareBracket_io";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_ll"] = 100464] = "SquareBracket_ll";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_rr"] = 100465] = "SquareBracket_rr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracket_rl"] = 100466] = "SquareBracket_rl";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracket_lr"] = 100467] = "CurlyBracket_lr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracket_l"] = 100468] = "CurlyBracket_l";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracket_r"] = 100469] = "CurlyBracket_r";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracket_uo"] = 100470] = "CurlyBracket_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracket_u"] = 100471] = "CurlyBracket_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracket_o"] = 100472] = "CurlyBracket_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracket_iuo"] = 100473] = "CurlyBracket_iuo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracket_iu"] = 100474] = "CurlyBracket_iu";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracket_io"] = 100475] = "CurlyBracket_io";
    EDMmlFormulaIndex[EDMmlFormulaIndex["VerticalBars_lr"] = 100476] = "VerticalBars_lr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["VerticalBars_l"] = 100477] = "VerticalBars_l";
    EDMmlFormulaIndex[EDMmlFormulaIndex["VerticalBars_r"] = 100478] = "VerticalBars_r";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleVerticalBars_lr"] = 100479] = "DoubleVerticalBars_lr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleVerticalBars_l"] = 100480] = "DoubleVerticalBars_l";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleVerticalBars_r"] = 100481] = "DoubleVerticalBars_r";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleBracket_lr"] = 100482] = "DoubleBracket_lr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleBracket_l"] = 100483] = "DoubleBracket_l";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleBracket_r"] = 100484] = "DoubleBracket_r";
    EDMmlFormulaIndex[EDMmlFormulaIndex["AngleBracket_lr"] = 100485] = "AngleBracket_lr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["AngleBracket_l"] = 100486] = "AngleBracket_l";
    EDMmlFormulaIndex[EDMmlFormulaIndex["AngleBracket_r"] = 100487] = "AngleBracket_r";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Floor_lr"] = 100488] = "Floor_lr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Ceiling_lr"] = 100489] = "Ceiling_lr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Floor_Ceiling"] = 100490] = "Floor_Ceiling";
    EDMmlFormulaIndex[EDMmlFormulaIndex["AngleBracketWithBar"] = 100491] = "AngleBracketWithBar";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ParenthesesWithBar"] = 100492] = "ParenthesesWithBar";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SquareBracketWithBar"] = 100493] = "SquareBracketWithBar";
    EDMmlFormulaIndex[EDMmlFormulaIndex["CurlyBracketWithBar"] = 100494] = "CurlyBracketWithBar";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LSquareBracketRParentheses"] = 100495] = "LSquareBracketRParentheses";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LParenthesesRSquareBracket"] = 100496] = "LParenthesesRSquareBracket";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LVerticalBarsRAngleBracket"] = 100497] = "LVerticalBarsRAngleBracket";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LAngleBracketRVerticalBars"] = 100498] = "LAngleBracketRVerticalBars";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SupMin"] = 100499] = "SupMin";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SupSec"] = 100500] = "SupSec";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SupMilliSec"] = 100501] = "SupMilliSec";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftMin"] = 100502] = "LeftMin";
    //single组
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverDot_s"] = 100503] = "OverDot_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverDoubleDot_s"] = 100504] = "OverDoubleDot_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverTripleDot_s"] = 100505] = "OverTripleDot_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverDotDot_s"] = 100506] = "OverDotDot_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverShortRightArr_s"] = 100507] = "OverShortRightArr_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverLeftRightArrow_s"] = 100508] = "OverLeftRightArrow_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverShortLeftArr_s"] = 100509] = "OverShortLeftArr_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverRightVector_s"] = 100510] = "OverRightVector_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverLeftRightVector_s"] = 100511] = "OverLeftRightVector_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverLeftVector_s"] = 100512] = "OverLeftVector_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclosedown_s"] = 100513] = "Enclosedown_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderDot_s"] = 100514] = "UnderDot_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderDoubleDot_s"] = 100515] = "UnderDoubleDot_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderTripleDot_s"] = 100516] = "UnderTripleDot_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderDotDot_s"] = 100517] = "UnderDotDot_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderShortRightArr_s"] = 100518] = "UnderShortRightArr_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderLeftRightArrow_s"] = 100519] = "UnderLeftRightArrow_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderShortLeftArr_s"] = 100520] = "UnderShortLeftArr_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderRightVector_s"] = 100521] = "UnderRightVector_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderLeftRightVector_s"] = 100522] = "UnderLeftRightVector_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderLeftVector_s"] = 100523] = "UnderLeftVector_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Encloseup_s"] = 100524] = "Encloseup_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverBar_s"] = 100525] = "OverBar_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverTilde_s"] = 100526] = "OverTilde_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_os"] = 100527] = "Parentheses_os";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverParentheses_s"] = 100528] = "OverParentheses_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverHat_s"] = 100529] = "OverHat_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverDownhat_s"] = 100530] = "OverDownhat_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SupMin_s"] = 100531] = "SupMin_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SupSec_s"] = 100532] = "SupSec_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SupMilliSec_s"] = 100533] = "SupMilliSec_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SupDegree_s"] = 100534] = "SupDegree_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Enclosehor_s"] = 100535] = "Enclosehor_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderBar_s"] = 100536] = "UnderBar_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderTilde_s"] = 100537] = "UnderTilde_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderParentheses_s"] = 100538] = "UnderParentheses_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Parentheses_us"] = 100539] = "Parentheses_us";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderHat_s"] = 100540] = "UnderHat_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderDownhat_s"] = 100541] = "UnderDownhat_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverMin_s"] = 100542] = "OverMin_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverLefmin_s"] = 100543] = "OverLefmin_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SupT_s"] = 100544] = "SupT_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Encloseupdown_s"] = 100545] = "Encloseupdown_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Last_s"] = 100546] = "Last_s";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverDot"] = 100547] = "OverDot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderDot"] = 100548] = "UnderDot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverDoubleDot"] = 100549] = "OverDoubleDot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderDoubleDot"] = 100550] = "UnderDoubleDot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverTripleDot"] = 100551] = "OverTripleDot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderTripleDot"] = 100552] = "UnderTripleDot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverDotDot"] = 100553] = "OverDotDot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderDotDot"] = 100554] = "UnderDotDot";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverBar"] = 100555] = "OverBar";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderBar"] = 100556] = "UnderBar";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverDoubleBar"] = 100557] = "OverDoubleBar";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderDoubleBar"] = 100558] = "UnderDoubleBar";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverShortRightArr"] = 100559] = "OverShortRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderShortRightArr"] = 100560] = "UnderShortRightArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverShortLeftArr"] = 100561] = "OverShortLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderShortLeftArr"] = 100562] = "UnderShortLeftArr";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverRightVector"] = 100563] = "OverRightVector";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderRightVector"] = 100564] = "UnderRightVector";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverLeftVector"] = 100565] = "OverLeftVector";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderLeftVector"] = 100566] = "UnderLeftVector";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverLeftRightArrow"] = 100567] = "OverLeftRightArrow";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderLeftRightArrow"] = 100568] = "UnderLeftRightArrow";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverLeftRightVector"] = 100569] = "OverLeftRightVector";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderLeftRightVector"] = 100570] = "UnderLeftRightVector";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverTilde"] = 100571] = "OverTilde";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderTilde"] = 100572] = "UnderTilde";
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverHat"] = 100573] = "OverHat";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderHat"] = 100574] = "UnderHat";
    // OverParentheses, UnderParentheses, // 小括弧
    // OverBracket, // 方括号
    EDMmlFormulaIndex[EDMmlFormulaIndex["OverShellBracket"] = 100575] = "OverShellBracket";
    EDMmlFormulaIndex[EDMmlFormulaIndex["UnderShellBracket"] = 100576] = "UnderShellBracket";
    // 箭头
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightArr_uo"] = 100577] = "RightArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightArr_u"] = 100578] = "RightArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightArr_o"] = 100579] = "RightArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftArr_uo"] = 100580] = "LeftArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftArr_u"] = 100581] = "LeftArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftArr_o"] = 100582] = "LeftArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftRightArr_uo"] = 100583] = "LeftRightArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftRightArr_u"] = 100584] = "LeftRightArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftRightArr_o"] = 100585] = "LeftRightArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightArrLeftArr_uo"] = 100586] = "RightArrLeftArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightArrLeftArr_u"] = 100587] = "RightArrLeftArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightArrLeftArr_o"] = 100588] = "RightArrLeftArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LRightArrSLeftArr_uo"] = 100589] = "LRightArrSLeftArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LRightArrSLeftArr_u"] = 100590] = "LRightArrSLeftArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LRightArrSLeftArr_o"] = 100591] = "LRightArrSLeftArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SRightArrLLeftArr_uo"] = 100592] = "SRightArrLLeftArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SRightArrLLeftArr_u"] = 100593] = "SRightArrLLeftArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SRightArrLLeftArr_o"] = 100594] = "SRightArrLLeftArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Equilibrium_uo"] = 100595] = "Equilibrium_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Equilibrium_u"] = 100596] = "Equilibrium_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["Equilibrium_o"] = 100597] = "Equilibrium_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LRightVerSLeftVer_uo"] = 100598] = "LRightVerSLeftVer_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LRightVerSLeftVer_u"] = 100599] = "LRightVerSLeftVer_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LRightVerSLeftVer_o"] = 100600] = "LRightVerSLeftVer_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SRightVerLLeftVer_uo"] = 100601] = "SRightVerLLeftVer_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SRightVerLLeftVer_u"] = 100602] = "SRightVerLLeftVer_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["SRightVerLLeftVer_o"] = 100603] = "SRightVerLLeftVer_o";
    // // 符号类型
    // Symbol_LRightArrSLeftArr, Symbol_SRightArrLLeftArr, // 长右箭头短左箭头 短右箭头长右箭头
    // Symbol_LRightVerSLeftVer, Symbol_SRightVerLLeftVer, // 长右向量短左向量 短右向量长右向量
    // 待定
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongLeftArr_uo"] = 100604] = "LongLeftArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongLeftArr_u"] = 100605] = "LongLeftArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongLeftArr_o"] = 100606] = "LongLeftArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftTeeArr_uo"] = 100607] = "LeftTeeArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftTeeArr_u"] = 100608] = "LeftTeeArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftTeeArr_o"] = 100609] = "LeftTeeArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleLeftArr_uo"] = 100610] = "DoubleLeftArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleLeftArr_u"] = 100611] = "DoubleLeftArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleLeftArr_o"] = 100612] = "DoubleLeftArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DbLongLeftArr_uo"] = 100613] = "DbLongLeftArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DbLongLeftArr_u"] = 100614] = "DbLongLeftArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DbLongLeftArr_o"] = 100615] = "DbLongLeftArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongRightArr_uo"] = 100616] = "LongRightArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongRightArr_u"] = 100617] = "LongRightArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongRightArr_o"] = 100618] = "LongRightArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightTeeArr_uo"] = 100619] = "RightTeeArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightTeeArr_u"] = 100620] = "RightTeeArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["RightTeeArr_o"] = 100621] = "RightTeeArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleRightArr_uo"] = 100622] = "DoubleRightArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleRightArr_u"] = 100623] = "DoubleRightArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DoubleRightArr_o"] = 100624] = "DoubleRightArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DbLongRightArr_uo"] = 100625] = "DbLongRightArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DbLongRightArr_u"] = 100626] = "DbLongRightArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["DbLongRightArr_o"] = 100627] = "DbLongRightArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongLeftRightArr_uo"] = 100628] = "LongLeftRightArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongLeftRightArr_u"] = 100629] = "LongLeftRightArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongLeftRightArr_o"] = 100630] = "LongLeftRightArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftArrRightArr_uo"] = 100631] = "LeftArrRightArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftArrRightArr_u"] = 100632] = "LeftArrRightArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LeftArrRightArr_o"] = 100633] = "LeftArrRightArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ReverseEquilibrium_uo"] = 100634] = "ReverseEquilibrium_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ReverseEquilibrium_u"] = 100635] = "ReverseEquilibrium_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ReverseEquilibrium_o"] = 100636] = "ReverseEquilibrium_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongRArrShortLArr_uo"] = 100637] = "LongRArrShortLArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongRArrShortLArr_u"] = 100638] = "LongRArrShortLArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["LongRArrShortLArr_o"] = 100639] = "LongRArrShortLArr_o";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ShortRArrLongLArr_uo"] = 100640] = "ShortRArrLongLArr_uo";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ShortRArrLongLArr_u"] = 100641] = "ShortRArrLongLArr_u";
    EDMmlFormulaIndex[EDMmlFormulaIndex["ShortRArrLongLArr_o"] = 100642] = "ShortRArrLongLArr_o";
    // 函数式
    EDMmlFormulaIndex[EDMmlFormulaIndex["fX"] = 100643] = "fX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["derivativeX"] = 100644] = "derivativeX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sinX"] = 100645] = "sinX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sin_X"] = 100646] = "sin_X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sin2X"] = 100647] = "sin2X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cosX"] = 100648] = "cosX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cos_X"] = 100649] = "cos_X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cos2X"] = 100650] = "cos2X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["tanX"] = 100651] = "tanX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["tan_X"] = 100652] = "tan_X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["tan2X"] = 100653] = "tan2X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["secX"] = 100654] = "secX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sec2X"] = 100655] = "sec2X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cscX"] = 100656] = "cscX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["csc2X"] = 100657] = "csc2X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cotX"] = 100658] = "cotX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["cot2X"] = 100659] = "cot2X";
    EDMmlFormulaIndex[EDMmlFormulaIndex["arcsinX"] = 100660] = "arcsinX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["arccosX"] = 100661] = "arccosX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["arctanX"] = 100662] = "arctanX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["arccotX"] = 100663] = "arccotX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["logX"] = 100664] = "logX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lgX"] = 100665] = "lgX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["lnX"] = 100666] = "lnX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["expX"] = 100667] = "expX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["eX"] = 100668] = "eX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["tenX"] = 100669] = "tenX";
    EDMmlFormulaIndex[EDMmlFormulaIndex["sup2"] = 100670] = "sup2";
    EDMmlFormulaIndex[EDMmlFormulaIndex["divided"] = 100671] = "divided";
    EDMmlFormulaIndex[EDMmlFormulaIndex["limX"] = 100672] = "limX";
    // 自定义公式 调用默认路径为QString(myformula/myFormula_%1).arg(i)的mml文本公式,例如myFormula_1是myformula/myFormula_1
    // myFormula_1, myFormula_2, myFormula_3, myFormula_4, myFormula_5,
    // myFormula_6, myFormula_7, myFormula_8, myFormula_9, myFormula_10,
    // myFormula_11, myFormula_12, myFormula_13, myFormula_14, myFormula_15,
    // myFormula_16, myFormula_17, myFormula_18, myFormula_19, myFormula_20,
    // myFormula_21, myFormula_22, myFormula_23, myFormula_24, myFormula_25,
    // myFormula_26, myFormula_27, myFormula_28, myFormula_29, myFormula_30,
    // 待完善
    // Test_Formula_1, Test_Formula_2
    EDMmlFormulaIndex[EDMmlFormulaIndex["end"] = 100673] = "end";
})(EDMmlFormulaIndex || (EDMmlFormulaIndex = {}));
//布局类型的分类
var EDMmlNodeLayoutType;
(function (EDMmlNodeLayoutType) {
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["None"] = 0] = "None";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["LeftRight"] = 1] = "LeftRight";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["Left"] = 2] = "Left";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["Right"] = 3] = "Right";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["WithBar"] = 4] = "WithBar";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["Over"] = 5] = "Over";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["Under"] = 6] = "Under";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["UnerOver"] = 7] = "UnerOver";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["IndexOver"] = 8] = "IndexOver";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["IndexUnder"] = 9] = "IndexUnder";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["IndexUnderOver"] = 10] = "IndexUnderOver";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["Enclose"] = 11] = "Enclose";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["Single"] = 12] = "Single";
    EDMmlNodeLayoutType[EDMmlNodeLayoutType["SupSingle"] = 13] = "SupSingle";
})(EDMmlNodeLayoutType || (EDMmlNodeLayoutType = {}));
//字体类型，解析带字体参数设置的mathml文本使用，一般情况下不涉及
var MathVariant;
(function (MathVariant) {
    MathVariant[MathVariant["NormalMV"] = 0] = "NormalMV";
    MathVariant[MathVariant["BoldMV"] = 1] = "BoldMV";
    MathVariant[MathVariant["ItalicMV"] = 2] = "ItalicMV";
    MathVariant[MathVariant["DoubleStruckMV"] = 4] = "DoubleStruckMV";
    MathVariant[MathVariant["ScriptMV"] = 8] = "ScriptMV";
    MathVariant[MathVariant["FrakturMV"] = 16] = "FrakturMV";
    MathVariant[MathVariant["SansSerifMV"] = 32] = "SansSerifMV";
    MathVariant[MathVariant["MonospaceMV"] = 64] = "MonospaceMV";
})(MathVariant || (MathVariant = {}));
// prefix 用于打开栅栏(fences)。（如果运算符是<mrow>具有多个参数的元素中的第一个参数，则它是默认值。）
// infix 用于分隔符。（如果运算符不包含在<mrow>元素中，则这是默认值。）
// postfix 关闭围栏(fences)。（如果运算符是<mrow>具有多个参数的元素中的最后一个参数，则它是默认值。）
var FormType;
(function (FormType) {
    FormType[FormType["PrefixForm"] = 0] = "PrefixForm";
    FormType[FormType["InfixForm"] = 1] = "InfixForm";
    FormType[FormType["PostfixForm"] = 2] = "PostfixForm";
})(FormType || (FormType = {})); // 表单类型
var ColAlign;
(function (ColAlign) {
    ColAlign[ColAlign["ColAlignLeft"] = 0] = "ColAlignLeft";
    ColAlign[ColAlign["ColAlignCenter"] = 1] = "ColAlignCenter";
    ColAlign[ColAlign["ColAlignRight"] = 2] = "ColAlignRight";
})(ColAlign || (ColAlign = {})); // 列对齐
var RowAlign;
(function (RowAlign) {
    RowAlign[RowAlign["RowAlignTop"] = 0] = "RowAlignTop";
    RowAlign[RowAlign["RowAlignCenter"] = 1] = "RowAlignCenter";
    RowAlign[RowAlign["RowAlignBottom"] = 2] = "RowAlignBottom";
    RowAlign[RowAlign["RowAlignAxis"] = 3] = "RowAlignAxis";
    RowAlign[RowAlign["RowAlignBaseline"] = 4] = "RowAlignBaseline";
})(RowAlign || (RowAlign = {}));
// 框架类型{无框架，实线框架，虚线框架}
var FrameType;
(function (FrameType) {
    FrameType[FrameType["FrameNone"] = 0] = "FrameNone";
    FrameType[FrameType["FrameSolid"] = 1] = "FrameSolid";
    FrameType[FrameType["FrameDashed"] = 2] = "FrameDashed";
})(FrameType || (FrameType = {}));
// 符号类型，用于布局时调整的判断依据，
// 其中 Normal不处理， Center居中
// (QT版本)Normal不处理 Arrow宽度*2 Uder贴底端绘制，Over贴顶端绘制，Symbol缩放运算符为统一大小, BoundingRect修改矩形框架 underover符号用Over
// (TS版本)Arrow作为箭头类符号处理，Center在上下布局中以居中方式处理，其余不做处理
var SymbolType;
(function (SymbolType) {
    SymbolType[SymbolType["Normal"] = 0] = "Normal";
    SymbolType[SymbolType["Arrow"] = 1] = "Arrow";
    SymbolType[SymbolType["Under"] = 2] = "Under";
    SymbolType[SymbolType["Over"] = 3] = "Over";
    SymbolType[SymbolType["Symbol"] = 4] = "Symbol";
    SymbolType[SymbolType["BoundingRect"] = 5] = "BoundingRect";
    SymbolType[SymbolType["Center"] = 6] = "Center";
})(SymbolType || (SymbolType = {}));
// 拉伸方式{不拉伸，水平拉伸，垂直拉伸，水平垂直拉伸}
var StretchDir;
(function (StretchDir) {
    StretchDir[StretchDir["NoStretch"] = 0] = "NoStretch";
    StretchDir[StretchDir["HStretch"] = 1] = "HStretch";
    StretchDir[StretchDir["VStretch"] = 2] = "VStretch";
    StretchDir[StretchDir["HVStretch"] = 3] = "HVStretch";
})(StretchDir || (StretchDir = {}));
//子节点操作类型
var ChildSpec;
(function (ChildSpec) {
    ChildSpec[ChildSpec["ChildAny"] = -1] = "ChildAny";
    ChildSpec[ChildSpec["ChildIgnore"] = -2] = "ChildIgnore";
    ChildSpec[ChildSpec["ImplicitMrow"] = -3] = "ImplicitMrow";
})(ChildSpec || (ChildSpec = {}));
// 目前支持的mathml字体，QT版本使用的参数
var MmlFont;
(function (MmlFont) {
    MmlFont[MmlFont["NormalFont"] = 0] = "NormalFont";
    MmlFont[MmlFont["FrakturFont"] = 1] = "FrakturFont";
    MmlFont[MmlFont["SansSerifFont"] = 2] = "SansSerifFont";
    MmlFont[MmlFont["ScriptFont"] = 3] = "ScriptFont";
    MmlFont[MmlFont["MonospaceFont"] = 4] = "MonospaceFont";
    MmlFont[MmlFont["DoublestruckFont"] = 5] = "DoublestruckFont";
})(MmlFont || (MmlFont = {}));
/**QT版本使用的参数
 * @brief The EDRendAdjustBits enum some adjustment bits for rendering stuff//枚举一些调整位来渲染东西
 */
var EDRendAdjustBits;
(function (EDRendAdjustBits) {
    EDRendAdjustBits[EDRendAdjustBits["Nothing"] = 0] = "Nothing";
    EDRendAdjustBits[EDRendAdjustBits["translateLspace"] = 1] = "translateLspace";
    EDRendAdjustBits[EDRendAdjustBits["translateTxt"] = 2] = "translateTxt";
})(EDRendAdjustBits || (EDRendAdjustBits = {}));
